### ISSUE TITLE
SceneLib2 build errors

### ISSUE THREAD

**Issue by LiliMeng** [hanmekim/SceneLib2#10]
Hi,

```
   All the previous installations before SceneLib2 worked good. After executing $cmake .. in the build directory of SceneLib2, the following errors occurred:

 Build type not set (defaults to debug)
```

-DCMAKE_BUILD_TYPE=Release for release
-- OpenCV ARCH: 
-- OpenCV RUNTIME: 
-- OpenCV STATIC: OFF
CMake Warning at /home/meng/opencv/cmake/OpenCVConfig.cmake:161 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  scenelib2/CMakeLists.txt:10 (FIND_PACKAGE)

CMake Error at scenelib2/CMakeLists.txt:10 (FIND_PACKAGE):
  Found package configuration file:

```
/home/meng/opencv/cmake/OpenCVConfig.cmake
```

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

-- Configuring incomplete, errors occurred!
See also "/home/meng/workspace/MonoSLAM2/SceneLib2/build/CMakeFiles/CMakeOutput.log".

Could anyone provide some suggestions? Thanks in advance!

**Comment by zizhaozhang** [comment]
Hi LiliMeng, what do your mean use ccmake .. Could you specific that?
