### ISSUE TITLE
libscenelib2.so: undefined reference to `glutBitmapCharacter'

### ISSUE THREAD

**Issue by somebodyus** [hanmekim/SceneLib2#13]
Dear author,

When I compile the example,  I have the following errors,

libscenelib2.so: undefined reference to `glutBitmapHelvetica12'

libscenelib2.so: undefined reference to `glutBitmapCharacter'

libscenelib2.so: undefined reference to `glutBitmapHelvetica18'

Could you help me?

Best Regards,
Jack

**Comment by hanmekim** [comment]
did you install OpenGL stuff correctly -- sudo apt-get install freeglut3-dev libglu-dev libglew-dev?

**Comment by somebodyus** [comment]
I have installed them. I use Ubuntu 14.04.3.

**Comment by hanmekim** [comment]
It seems there is an issue linking to the glut library on your PC -- unfortunately, I don't think I can help you this out as I can't replicate the issue on my machine.

**Comment by somebodyus** [comment]
I tested the Pangolin samples in my home directory. The sample code can link the glut library and work well.

**Comment by hanmekim** [comment]
Hmm.. then why don't you compare the Pangolin's cmake file and the SceneLib2 one to figure out what change needed on your machine?

**Comment by somebodyus** [comment]
I solved the problem using old version of Pangolin. 
And compile Pangolin using the command,
cmake -DCPP11_NO_BOOST=1 -DFORCE_GLUT=1 ..

**Comment by hanmekim** [comment]
should be fine with the latest commit.
