### ISSUE TITLE
A dummy question: Can monocular SLAM provide scale information?

### ISSUE THREAD

**Issue by somebodyus** [hanmekim/SceneLib2#14]
A dummy question: 

Can monocular SLAM provide scale information?

**Comment by ahundt** [comment]
I don't think any multiple view geometry system can derive scale without some physical reference object or scale provided from outside. Just had an exam on that yesterday so I'm no expert but I think I'm answering correctly.

**Comment by hanmekim** [comment]
Unlike RGB-D or stereo, the absolute scale of the world cannot be recovered by monocular SLAM -- all geometrical metric units are only defined up to scale.
