### ISSUE TITLE
compiling error, using Pangolin headers

### ISSUE THREAD

**Issue by souilehbhn** [hanmekim/SceneLib2#15]
Hi,
when I build the project using make, I have this error:
/usr/local/include/pangolin/var/varvalue.h: In instantiation of ‘void pangolin::VarValue<T>::Init() [with T = int]’:
/usr/local/include/pangolin/var/varvalue.h:56:14:   required from ‘pangolin::VarValue<T>::VarValue(const T&) [with T = int]’
/usr/local/include/pangolin/var/var.h:169:20:   required from ‘pangolin::Var<T>::Var(const string&, const T&, bool) [with T = int; std::string = std::basic_string<char>]’
/home/salah/linaro/SceneLib2/SceneLib2/scenelib2/monoslam.cpp:1584:94:   required from here
/usr/local/include/pangolin/var/varvalue.h:100:23: error: ‘class pangolin::VarValue<int>’ has no member named ‘str’
             this->str = (VarValueT<std::string>*)this;
                       ^
/usr/local/include/pangolin/var/varvalue.h:103:23: error: ‘class pangolin::VarValue<int>’ has no member named ‘str’
             this->str = str_ptr;

shall I change the line 108 of the header file varvalue.h

VarValueT<std::string>* str_ptr;

to 

VarValueT<std::string>* str;

if not what should I do?

**Comment by hanmekim** [comment]
should be fine with the latest commit.
