### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by PetrBarborka** [hanmekim/SceneLib2#16]
Hi, 
I am trying to run examples/MonoSlamSceneLib1 on mac osx 10.10. After building sucsessfully I get this:

```
Tyler@Tylers-MBP ~/dev/SceneLib2/SceneLib2/BUILD/examples:  ./MonoSlamSceneLib1
    libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: provided directory      doesn't exist!
    [1]    81348 abort      ./MonoSlamSceneLib1 
```

I have no clue what that error actually means ( what directory? ) and googling didn't help. Maybe you would know what to do with it? 

**update:**
When I open the file by double clicking it, I also get:

```
Unable to open '../../data/SceneLib2.cfg' for configuration data
```

in addition to the above. The file is there, I can open it with vim and the permissions are 777.

Thanks for your attention,
Petr

**Comment by hanmekim** [comment]
Please refer to the "How to use" section in the readme file, and basically, you need to modify paths or directories according to your machine. Thanks.
