### ISSUE TITLE
example "core dumped" after activate the "Toggle Tracking" button.   

### ISSUE THREAD

**Issue by lligen** [hanmekim/SceneLib2#17]
hi, 
    i' m in ubuntu 14.04,  when running the example, i got "core dumped" after activate the "Toggle Tracking" button.  
   cmake and make process has no problem.
   need help~~  thank you～～

**Comment by hanmekim** [comment]
Could you give me more information -- whole error messages might help. Also, could you make sure there is no problem with loading the inputs to the application at start (e.g. configuration file and input image sequence)?

**Comment by lligen** [comment]
hi,
 i got the problem.  i run the program in the wrong directory...which lead to  the first 4 patches to be null patch and core dumped... thanks for your code~~~~
