### ISSUE TITLE
Camera calibration problem

### ISSUE THREAD

**Issue by liming0791** [hanmekim/SceneLib2#18]
Hello.

I successfully ran the example with a handled USB webcam, but the feature tracking and pose estimation were terrible. Then I ran the example on provided image files, and it worked well. So I guess the problem is camera calibration.

I am confused with the camera parameters in `SceneLib2.cfg`, because usually there are 4 intrinsic matrix parameters and 5 distortion parameters but actually there are 4 intrinsic matrix parameters  and 2 distortion parameters (I guess). Why ?

Besides, my camera provide 640x480 image size, and in `usbcam_grabber` it will be resized to 320x240. So what should I do about my camera calibration parameters ?

**Comment by hanmekim** [comment]
Hi,

There is only one radial distortion parameter, kd1, and it is based on the equations (8-10) on the original MonoSLAM PAMI paper. If you want to know more about the radial distortion model, please refer to its reference [44].

Yes, it is resized to 320x240 (same as the original implementation), and you can simply scale your intrinsic parameters accordingly too.

Many thanks,
Hanme

**Comment by liming0791** [comment]
@hanmekim  Thanks a lot !

**Comment by Saikat2019** [comment]
this a very good tutorial on camera calibration [https://www.youtube.com/watch?v=WvGcxJ1L3NM](url) , helped me a lot in my project, you can refer to this one
